### ISSUE TITLE
DisableTouchBar is not persistent when the SIP is enable back

### ISSUE THREAD

**Issue by m-zheng** [giovannigravili/DisableTouchBar#1]
Hi, thanks for sharing your method to disable touch bar. Do I need to keep SIP disabled all the time to disable touch bar? I found touch bar is enabled automatically when the SIP is enabled back. If yes, do you know any way to walk around it as SIP is suggested to be enabled for security reasons?

**Comment by giovannigravili** [comment]
Hi, thanks for your comment. I honestly keep my SIP disabled because it's a non-issue for me. I don't know any other workarounds personally.
